import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
  EXPORT_CLIENTS,
  EXPORT_CLIENT_IDS,
  clientConfigTransfer,
  exportClientLabelKey,
  parseClientConfigEnvelope,
  type ClientConfigEnvelope,
} from "../src/api-access/export-clients.ts";
import { clientConfigDetailView } from "../src/components/apikeys-workspace/client-config-resource.ts";
import { translate } from "../src/i18n/catalogs.ts";
import type { TFn } from "../src/i18n/shared.ts";

const guiRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(guiRoot, "..");
const workspaceDir = path.join(guiRoot, "src", "components", "apikeys-workspace");

test("the browser client list stays in step with the Go export authority", () => {
  const go = readFileSync(path.join(repoRoot, "internal", "export", "export.go"), "utf8");
  const declaration = /var ClientIDs = \[\]string\{([^}]*)\}/.exec(go);
  assert.ok(declaration, "ClientIDs declaration not found in internal/export/export.go");
  const goIds = declaration[1]
    .split(",")
    .map(entry => entry.trim().replace(/^"|"$/g, ""))
    .filter(entry => entry.length > 0);
  assert.deepEqual([...EXPORT_CLIENT_IDS], goIds);
});

test("every export client has a translated label and only real assets as marks", () => {
  for (const client of EXPORT_CLIENTS) {
    const label = translate("en", exportClientLabelKey(client.id));
    assert.equal(typeof label, "string");
    assert.notEqual(label, exportClientLabelKey(client.id), `${client.id} label key is not translated`);
    assert.ok(label.trim().length > 0, `${client.id} label is empty`);
    if (client.mark) {
      assert.match(client.mark, /^\/provider-icons\/[\w-]+\.svg$/);
      assert.ok(
        existsSync(path.join(guiRoot, "public", client.mark.replace(/^\//, ""))),
        `${client.id} mark is missing from gui/public`,
      );
    }
  }
  assert.equal(EXPORT_CLIENT_IDS.length, new Set(EXPORT_CLIENT_IDS).size);
});

const TOML_TEXT = [
  "[providers.benes]",
  "api = 127.0.0.1:23100/v1",
  "models = gpt-5.4",
].join("\n");

function tomlEnvelope(): ClientConfigEnvelope {
  return {
    client: "kimi",
    filename: "kimi-config.toml",
    destination: "~/.kimi-code/config.toml",
    apiKeyEnv: "",
    exportHint: "Kimi Code reads credentials from its config file.",
    modelCount: 3,
    modelsWithoutLimits: 1,
    format: "toml",
    mediaType: "application/toml",
    text: TOML_TEXT,
    config: { providers: { benes: { api: "127.0.0.1:23100/v1", models: ["gpt-5.4"] } } },
  };
}

test("a non-JSON envelope transfers the listener's exact bytes", () => {
  const envelope = tomlEnvelope();
  const transfer = clientConfigTransfer(envelope);
  assert.equal(transfer.text, TOML_TEXT);
  assert.equal(transfer.filename, "kimi-config.toml");
  assert.equal(transfer.mediaType, "application/toml");
  // The generated text is TOML. Re-serializing `config` would emit JSON, which
  // is the failure this contract exists to prevent.
  assert.throws(() => JSON.parse(transfer.text));
  assert.notEqual(transfer.text, JSON.stringify(envelope.config));
});

test("the detail view previews the generated bytes instead of re-encoding config", () => {
  // Architecture boundary: the listener owns the generated file. The pane's
  // preview and the transfer its two actions move are resolved together, so the
  // bytes on screen are the bytes a reader copies, and neither can be rebuilt
  // from `config` — which would emit JSON for the non-JSON clients.
  const echo = ((key: string, vars?: Record<string, unknown>) =>
    translate("en", key as never, vars as never)) as unknown as TFn;
  const envelope = tomlEnvelope();
  const view = clientConfigDetailView(envelope, true, echo);
  assert.equal(view.preview.text, TOML_TEXT);
  assert.equal(view.transfer.text, TOML_TEXT);
  assert.equal(view.transfer.filename, "kimi-config.toml");
  assert.equal(view.transfer.mediaType, "application/toml");
  assert.equal(view.preview.text, clientConfigTransfer(envelope).text);

  // Neither surface may re-serialize, and the download mechanics stay with the
  // owner that holds the transfer rather than being rebuilt in the panel.
  const detail = readFileSync(path.join(workspaceDir, "ClientConfigDetail.tsx"), "utf8");
  assert.equal(detail.includes("JSON.stringify"), false);
  assert.equal(detail.includes("envelope.config"), false);
  const panel = readFileSync(path.join(workspaceDir, "ClientConfigPanel.tsx"), "utf8");
  assert.equal(panel.includes("JSON.stringify"), false);
  assert.equal(panel.includes("createObjectURL"), false);
});

test("the envelope parser accepts a well-formed payload and rejects the rest", () => {
  const envelope = tomlEnvelope();
  const wire: Record<string, unknown> = { ...envelope };
  delete wire.client;
  assert.deepEqual(parseClientConfigEnvelope(wire, "kimi")?.text, TOML_TEXT);

  const broken: Array<Partial<Record<string, unknown>>> = [
    { filename: "" },
    { filename: undefined },
    { mediaType: undefined },
    { text: undefined },
    { destination: 7 },
    { apiKeyEnv: null },
    { exportHint: undefined },
    { format: undefined },
    { modelCount: "3" },
    { modelsWithoutLimits: undefined },
  ];
  for (const override of broken) {
    assert.equal(parseClientConfigEnvelope({ ...wire, ...override }, "kimi"), null);
  }
  assert.equal(parseClientConfigEnvelope(null, "kimi"), null);
  assert.equal(parseClientConfigEnvelope("{}", "kimi"), null);
});
