import type { TKey } from "../../i18n/shared";
import type {
  HarnessAuth,
  HarnessCapabilityId,
  HarnessHistoryRow,
  HarnessRecord,
  HarnessSettings,
} from "./types";

const FULL_CAPS: Record<HarnessCapabilityId, boolean> = {
  sendMessages: true,
  toolCalls: true,
  readFiles: true,
  writeFiles: true,
  shell: true,
  browser: true,
  mcp: true,
  sessions: true,
};

const CLI_CAPS: Record<HarnessCapabilityId, boolean> = {
  ...FULL_CAPS,
  browser: false,
};

const LIGHT_CAPS: Record<HarnessCapabilityId, boolean> = {
  sendMessages: true,
  toolCalls: true,
  readFiles: true,
  writeFiles: false,
  shell: false,
  browser: false,
  mcp: true,
  sessions: true,
};

const DEFAULT_SETTINGS: HarnessSettings = {
  autoDetect: true,
  autoApply: true,
  retainSnapshot: true,
  allowRestart: false,
};

function oauth(methodKey: TKey, clientId: string, scopes: string[]): HarnessAuth {
  return { kind: "oauth", methodKey, clientId, scopes, token: "valid" };
}

function noAuth(): HarnessAuth {
  return {
    kind: "none",
    methodKey: "harnesses.auth.none",
    clientId: null,
    scopes: [],
    token: "none",
  };
}

function row(
  id: string,
  kind: HarnessHistoryRow["kind"],
  snapshot: string,
  at: string,
  noteKey: TKey,
): HarnessHistoryRow {
  return { id, kind, snapshot, at, noteKey, restorable: true };
}

export function seedHarnesses(): HarnessRecord[] {
  return [
    {
      id: "claude-desktop",
      nameKey: "claudeDesktop.title",
      installed: true,
      applied: true,
      running: true,
      issue: "update-needed",
      drift: true,
      detectMethod: "auto",
      detectPath: "C:\\Users\\ws\\AppData\\Local\\AnthropicClaude\\claude.exe",
      configPath: "C:\\Users\\ws\\AppData\\Roaming\\Claude\\claude_desktop_config.json",
      logPath: "C:\\Users\\ws\\AppData\\Roaming\\Claude\\logs",
      snapshotId: "snap_7c4e2a91",
      lastDetectedAt: "2026-08-23T20:41:00.000Z",
      lastAppliedAt: "2026-08-22T18:12:00.000Z",
      auth: oauth("harnesses.auth.claudeOAuth", "claude-desktop.benes", ["profile", "sessions", "tools"]),
      capabilities: FULL_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [
        row("h-cd-1", "apply", "snap_7c4e2a91", "2026-08-22T18:12:00.000Z", "harnesses.note.autoApply"),
        row("h-cd-2", "apply", "snap_1f90bb3c", "2026-08-19T11:03:00.000Z", "harnesses.note.userApply"),
      ],
    },
    {
      id: "claude",
      nameKey: "integrations.tab.claude",
      installed: true,
      applied: true,
      running: true,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: "claude",
      configPath: "C:\\Users\\ws\\.claude.json",
      logPath: "C:\\Users\\ws\\.claude\\logs",
      snapshotId: "snap_b8d21e04",
      lastDetectedAt: "2026-08-23T20:40:00.000Z",
      lastAppliedAt: "2026-08-21T16:44:00.000Z",
      auth: oauth("harnesses.auth.claudeOAuth", "claude-code.benes", ["profile", "sessions", "tools"]),
      capabilities: CLI_CAPS,
      settings: { ...DEFAULT_SETTINGS, allowRestart: true },
      history: [row("h-cl-1", "apply", "snap_b8d21e04", "2026-08-21T16:44:00.000Z", "harnesses.note.userApply")],
    },
    {
      id: "codex",
      nameKey: "integrations.tab.codex",
      installed: true,
      applied: true,
      running: true,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: "codex",
      configPath: "C:\\Users\\ws\\.codex\\config.toml",
      logPath: "C:\\Users\\ws\\.codex\\log",
      snapshotId: "snap_e21aa0f6",
      lastDetectedAt: "2026-08-23T20:39:00.000Z",
      lastAppliedAt: "2026-08-20T12:08:00.000Z",
      auth: oauth("harnesses.auth.codexOAuth", "codex.benes", ["profile", "sessions"]),
      capabilities: CLI_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [row("h-cx-1", "apply", "snap_e21aa0f6", "2026-08-20T12:08:00.000Z", "harnesses.note.autoApply")],
    },
    {
      id: "dsh",
      nameKey: "integrations.tab.dsh",
      installed: true,
      applied: true,
      running: false,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: "dsh",
      configPath: "C:\\Users\\ws\\.dsh\\config.json",
      logPath: "C:\\Users\\ws\\.dsh\\logs",
      snapshotId: "snap_44c0198a",
      lastDetectedAt: "2026-08-23T19:12:00.000Z",
      lastAppliedAt: "2026-08-18T08:22:00.000Z",
      auth: noAuth(),
      capabilities: LIGHT_CAPS,
      settings: { ...DEFAULT_SETTINGS, autoApply: false },
      history: [row("h-dsh-1", "apply", "snap_44c0198a", "2026-08-18T08:22:00.000Z", "harnesses.note.userApply")],
    },
    {
      id: "opencode",
      nameKey: "integrations.tab.opencode",
      installed: true,
      applied: false,
      running: false,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: "opencode",
      configPath: "C:\\Users\\ws\\.config\\opencode\\benes.json",
      logPath: "C:\\Users\\ws\\.config\\opencode\\logs",
      snapshotId: null,
      lastDetectedAt: "2026-08-23T20:10:00.000Z",
      lastAppliedAt: null,
      auth: noAuth(),
      capabilities: CLI_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [],
    },
    {
      id: "pi",
      nameKey: "integrations.tab.pi",
      installed: true,
      applied: false,
      running: null,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: "pi",
      configPath: "C:\\Users\\ws\\.pi\\config.toml",
      logPath: "C:\\Users\\ws\\.pi\\logs",
      snapshotId: null,
      lastDetectedAt: "2026-08-23T17:02:00.000Z",
      lastAppliedAt: null,
      auth: noAuth(),
      capabilities: LIGHT_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [],
    },
    {
      id: "prime",
      nameKey: "integrations.tab.prime",
      installed: true,
      applied: false,
      running: null,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: "prime",
      configPath: "C:\\Users\\ws\\.prime\\agent\\models.json",
      logPath: "C:\\Users\\ws\\.prime\\logs",
      snapshotId: null,
      lastDetectedAt: "2026-08-23T17:02:00.000Z",
      lastAppliedAt: null,
      auth: noAuth(),
      capabilities: LIGHT_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [],
    },
    {
      id: "omp",
      nameKey: "integrations.tab.omp",
      installed: true,
      applied: false,
      running: null,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: "omp",
      configPath: "C:\\Users\\ws\\.omp\\benes.json",
      logPath: "C:\\Users\\ws\\.omp\\logs",
      snapshotId: null,
      lastDetectedAt: "2026-08-22T21:40:00.000Z",
      lastAppliedAt: null,
      auth: noAuth(),
      capabilities: LIGHT_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [],
    },
    {
      id: "hermes",
      nameKey: "integrations.tab.hermes",
      installed: true,
      applied: false,
      running: false,
      issue: "conflict",
      drift: false,
      detectMethod: "auto",
      detectPath: "hermes",
      configPath: "C:\\Users\\ws\\.hermes\\config.json",
      logPath: "C:\\Users\\ws\\.hermes\\logs",
      snapshotId: "snap_9aa1c3ee",
      lastDetectedAt: "2026-08-23T14:55:00.000Z",
      lastAppliedAt: "2026-08-12T10:17:00.000Z",
      auth: noAuth(),
      capabilities: CLI_CAPS,
      settings: { ...DEFAULT_SETTINGS, autoApply: false },
      history: [row("h-he-1", "apply", "snap_9aa1c3ee", "2026-08-12T10:17:00.000Z", "harnesses.note.userApply")],
    },
    {
      id: "openclaw",
      nameKey: "integrations.tab.openclaw",
      installed: true,
      applied: false,
      running: null,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: "openclaw",
      configPath: "C:\\Users\\ws\\.openclaw\\benes.json",
      logPath: "C:\\Users\\ws\\.openclaw\\logs",
      snapshotId: null,
      lastDetectedAt: "2026-08-21T08:30:00.000Z",
      lastAppliedAt: null,
      auth: noAuth(),
      capabilities: LIGHT_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [],
    },
    {
      id: "kimi",
      nameKey: "integrations.tab.kimi",
      installed: true,
      applied: false,
      running: null,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: "kimi",
      configPath: "C:\\Users\\ws\\.kimi\\config.json",
      logPath: "C:\\Users\\ws\\.kimi\\logs",
      snapshotId: null,
      lastDetectedAt: "2026-08-20T19:18:00.000Z",
      lastAppliedAt: null,
      auth: noAuth(),
      capabilities: LIGHT_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [],
    },
    {
      id: "gajae",
      nameKey: "integrations.tab.gajae",
      installed: true,
      applied: false,
      running: null,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: "gajae",
      configPath: "C:\\Users\\ws\\.gajae\\config.json",
      logPath: "C:\\Users\\ws\\.gajae\\logs",
      snapshotId: null,
      lastDetectedAt: "2026-08-19T13:47:00.000Z",
      lastAppliedAt: null,
      auth: noAuth(),
      capabilities: LIGHT_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [],
    },
    {
      id: "grok",
      nameKey: "integrations.tab.grok",
      installed: false,
      applied: false,
      running: null,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: null,
      configPath: null,
      logPath: null,
      snapshotId: null,
      lastDetectedAt: null,
      lastAppliedAt: null,
      auth: noAuth(),
      capabilities: CLI_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [],
    },
    {
      id: "mcode",
      nameKey: "integrations.tab.mcode",
      installed: false,
      applied: false,
      running: null,
      issue: "none",
      drift: false,
      detectMethod: "auto",
      detectPath: null,
      configPath: null,
      logPath: null,
      snapshotId: null,
      lastDetectedAt: null,
      lastAppliedAt: null,
      auth: noAuth(),
      capabilities: LIGHT_CAPS,
      settings: { ...DEFAULT_SETTINGS },
      history: [],
    },
  ];
}

export function newSnapshotId(): string {
  const bytes = new Uint8Array(4);
  crypto.getRandomValues(bytes);
  return `snap_${[...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("")}`;
}

export function newHistoryId(): string {
  return `h_${crypto.randomUUID()}`;
}
