package claude

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/Wibias/Benes/internal/store/atomicfile"
)

const (
	ownedPrefix     = "benes-"
	generatedMarker = "generated-by: benes"
	noModelArg      = "NOTE: this agent's real model is pinned by the benes proxy — the `model` argument is ignored. Pass model: \"haiku\" as a placeholder (or omit it); routing is unaffected either way."
)

var DefaultSubagentModels = []string{"gpt-5.5", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.4-mini"}

var nonName = regexp.MustCompile(`[^a-z0-9]+`)

type AgentDef struct {
	File        string
	Name        string
	Model       string
	Description string
	Effort      string
}

func sanitizeName(value string) string {
	cleaned := strings.Trim(nonName.ReplaceAllString(strings.ToLower(value), "-"), "-")
	if cleaned == "" {
		return "model"
	}
	return cleaned
}

func BuildAgentDefs(settings CodeSettings, roster []string, configDir string, rosterSet bool) []AgentDef {
	if settings.Enabled != nil && !*settings.Enabled {
		return nil
	}
	if settings.InjectAgents != nil && !*settings.InjectAgents {
		return nil
	}
	models := roster
	if !rosterSet {
		models = DefaultSubagentModels
	}
	defs := make([]AgentDef, 0, 6)
	used := map[string]struct{}{}
	covered := map[string]struct{}{}
	for i, entry := range models {
		if i >= 5 {
			break
		}
		entry = strings.TrimSpace(entry)
		if entry == "" {
			continue
		}
		id := entry
		provider := "native"
		if slash := strings.Index(entry, "/"); slash > 0 {
			provider = entry[:slash]
			id = entry[slash+1:]
		}
		alias := SurfaceAlias(entry)
		bare := strings.ToLower(alias)
		if _, ok := covered[bare]; ok {
			continue
		}
		covered[bare] = struct{}{}
		name := sanitizeName(id)
		unique := name
		for n := 2; ; n++ {
			if _, ok := used[unique]; !ok {
				break
			}
			unique = name + "-" + strconv.Itoa(n)
		}
		used[unique] = struct{}{}
		defs = append(defs, AgentDef{
			File:        ownedPrefix + unique + ".md",
			Name:        ownedPrefix + unique,
			Model:       alias,
			Description: "Delegate work to " + id + " (" + provider + ") via benes routing. General-purpose worker/explorer on that model. " + noModelArg,
			Effort:      "",
		})
	}
	selfModel := pickerDefaultModel(configDir)
	if selfModel == "" {
		selfModel = strings.TrimSpace(settings.Model)
	}
	if selfModel != "" {
		defs = append(defs, AgentDef{
			File:        ownedPrefix + "self.md",
			Name:        ownedPrefix + "self",
			Model:       selfModel,
			Description: "Self-clone: delegate to your default main model (" + selfModel + "), synced from the /model picker at launch. " + noModelArg,
		})
	}
	return defs
}

func pickerDefaultModel(configDir string) string {
	raw, err := os.ReadFile(filepath.Join(configDir, "settings.json"))
	if err != nil {
		return ""
	}
	var parsed struct {
		Model string `json:"model"`
	}
	if json.Unmarshal(raw, &parsed) != nil {
		return ""
	}
	return strings.TrimSpace(parsed.Model)
}

func renderAgentDef(def AgentDef) string {
	lines := []string{
		"---",
		`name: ` + jsonString(def.Name),
		`description: ` + jsonString(def.Description),
		`model: ` + jsonString(def.Model),
	}
	if def.Effort != "" {
		lines = append(lines, `effort: `+jsonString(def.Effort))
	}
	lines = append(lines,
		"---",
		"",
		"<!-- "+generatedMarker+" -->",
		"<!-- benes-route: "+def.Model+" -->",
		"",
		"You are a delegated worker running on `"+def.Model+"` through the local benes proxy.",
		"IDENTITY: your ACTUAL underlying model is `"+def.Model+"` — the benes proxy routes this",
		"session there regardless of what model name the Claude Code harness displays or claims.",
		"If asked which model you are, answer with the id above; do not guess a Claude model name.",
		"",
		"Complete the dispatched task directly and report results concisely. This file is",
		"auto-generated by benes (`benes claude`) from the featured subagent roster —",
		"manual edits will be overwritten; remove the model from the roster to drop it.",
		"",
	)
	return strings.Join(lines, "\n")
}

func jsonString(v string) string {
	raw, _ := json.Marshal(v)
	return string(raw)
}

func SyncAgentDefs(defs []AgentDef, configDir string) error {
	dir := filepath.Join(configDir, "agents")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	keep := map[string]struct{}{}
	for _, def := range defs {
		keep[def.File] = struct{}{}
	}
	entries, _ := os.ReadDir(dir)
	for _, entry := range entries {
		name := entry.Name()
		if !strings.HasPrefix(name, ownedPrefix) || !strings.HasSuffix(name, ".md") {
			continue
		}
		if _, ok := keep[name]; ok {
			continue
		}
		path := filepath.Join(dir, name)
		if ownedFile(path) {
			_ = os.Remove(path)
		}
	}
	for _, def := range defs {
		path := filepath.Join(dir, def.File)
		if st, err := os.Lstat(path); err == nil {
			if st.Mode()&os.ModeSymlink != 0 || !ownedFile(path) {
				continue
			}
		}
		if err := atomicfile.Write(path, []byte(renderAgentDef(def)), atomicfile.Options{Mode: 0o644}); err != nil {
			return err
		}
	}
	return nil
}

func ownedFile(path string) bool {
	st, err := os.Lstat(path)
	if err != nil || !st.Mode().IsRegular() {
		return false
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(raw), generatedMarker)
}
